### ISSUE TITLE
Restrict Status Changes

### ISSUE THREAD

**Issue by dakotamcinnis** [PatrickVuscan/RequestToPay_FrontEnd#40]
At the moment, any status can be set at any time. For example, a driver is able to set an invoice to delivered before it is arrived or paid.

The business logic of the desired status progression should be reflected in what functionality a user is provided.

**Comment by dionysuscho** [comment]
Solved this by restricting button actions on OrderAction menu.  
Cannot pay without approval.
Cannot arrive without approval.
Cannot deliver without arrival.
